version: "3.8"
   
services:

  pgdb:
    image: postgres
    container_name: pgdb
    environment:
      - POSTGRES_DB=formsdb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password123
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432