# Generated by Django 3.2.8 on 2021-10-15 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userform', '0002_userentry_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userentry',
            name='uuid',
            field=models.CharField(default='asdhjfsjahdgf', editable=False, max_length=50),
            preserve_default=False,
        ),
    ]
