# Generated by Django 3.2.8 on 2021-10-15 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userform', '0005_alter_userentry_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userentry',
            name='uuid',
            field=models.CharField(editable=False, max_length=50),
        ),
    ]
