# Generated by Django 3.2.8 on 2021-10-15 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userform', '0006_alter_userentry_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userentry',
            name='uuid',
            field=models.CharField(max_length=50),
        ),
    ]
