# Generated by Django 3.2.8 on 2021-10-15 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userform', '0007_alter_userentry_uuid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.AlterField(
            model_name='userentry',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
